spring:
  application:
    name: backend
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    driver-class-name: org.postgresql.Driver
  sql.init.mode: always
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    schemas: wall_backend_flyway
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus